### ISSUE TITLE
The draggable area on elements with scrollbars is shifted over to the right

### ISSUE THREAD

**Issue by brianhoy** [mattlewis92/angular2-resizable#19] opened 2016-08-31 19:47 UTC
If you have an element with a scrollbar, and you try to make the right side of it draggable, you have to actually click and drag an area to the right of the scrollbar for it to actually work.
![Demo](https://i.gyazo.com/1b0d36c164db662f7e7229011f3c87de.gif)
For some reason the recording displayed the resizing cursor a little more to the right than it actually is. When I begin dragging the edge the first time, it's actually directly on the edge, not to the right like the gif shows. The normal cursor seems to be displayed fine though.

**Comment by mattlewis92** [comment] 2016-09-01 13:00
It works fine for me on a mac, what browser / OS are you using? Does this demo work ok for you? http://www.webpackbin.com/V1oEzfboZ

**Comment by brianhoy** [comment] 2016-09-01 21:50
The demo works fine and I'm using Chrome on Windows 10. If it's any help, you can see the site [here]( https://brianhoy.github.io/noise-visualizer/). The component that's using the resizable module is located [here](https://github.com/brianhoy/noise-visualizer/blob/gh-pages/src/components/sidebar/sidebar.component.ts). I'm not sure what's causing this and if it's a bug or if there's something wrong with the way I did it, but removing the sidebar seems to fix it. In the github pages site I linked I set overflow-y: auto so that the scrollbar only shows when the tabs are expanded, allowing you to test it with and without the sidebar. Since this issue seems to be specific to me I would understand if you wanted to close this issue.

**Comment by mattlewis92** [comment] 2016-09-02 07:00
I couldn't reproduce it on your demo either, maybe it's an issue with window scrollbars? Although it seems odd that my demo would work ok for you. If you can reproduce it on this repos demo and want to hack about with it to see if you can work out what's going on, the logic is here: https://github.com/mattlewis92/angular2-resizable/blob/master/src/resizable.directive.ts#L119

Otherwise I'm going to close this as there's not much else I can really do to help.

**Closed by mattlewis92** 2016-09-02 07:00 UTC
